import angular from 'angular';
import 'angular-ui-router';
import 'angular-ui-bootstrap';
import 'angular-gravatar';
import 'angular-smart-table';
import 'angular-socket-io';
import 'angular-animate';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our templates file (generated by Gulp)
import './config/app.templates';

import './layout';
import './home';
import './admin';
import './auth';
import './components';
import './settings';


import './services';

const requires = [
	'ui.router',
	'ui.bootstrap',
	'ui.gravatar',
  'ngAnimate',
  'smart-table',
  'templates',
  'app.services',
  'app.layout',
  'app.components',
  'app.auth',
  'app.admin',
  'app.home',
  'app.settings',
  'btford.socket-io'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});