import angular from 'angular';
import 'angular-ui-router';
import 'angular-ui-bootstrap';
import 'angular-gravatar';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our templates file (generated by Gulp)
import './config/app.templates';

import './layout';
import './home';
import './auth';
import './components';


import './services';

const requires = [
	'ui.router',
	'ui.bootstrap',
	'ui.gravatar',
  'templates',
  'app.services',
  'app.layout',
  'app.components',
  'app.auth',
  'app.home'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});